name: "demo github actions"
on:
  push:
    # paths:
      # - '!README.md'
      # - '!docs/**'
      # - '**.js'
    branches:
      - 'develop'
      # - 'release/**'
      # - '!dev/**'
  # pull_request:
  #   types: [opened, reopened, synchronize]

  # workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello work
