name: "demo github actions"
on:
  push:
    paths:
      - '!README.md'
      - '**.js'
    branches:
      - 'develop'
      # - 'release/**'
      # - '!dev/**'
  # pull_request:
  #   types: [opened, reopened, synchronize]
  pull_request:
    types:
      - "opened"
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello work
  # hello_1: 
  #   needs: [hello]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo hello work
