name: "demo github actions"
on:
  push:
    # paths:
      # - "!README.md"
      # - "!docs/**"
      # - "**.js"
    branches:
      - "develop"
      # - "release/**"
      # - "!dev/**"
  # workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello work
