name: "demo github actions"
on:
  push:
    paths:
      - "!README.md"
      - "!docs/**"
      - "**.js"
    branches:
      - "develop"
      - "release/**"
      # - "!dev/**"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello work
